---
params:
  dataset: NULL 
  target: NULL
  regroup: TRUE
title: "`r config_report$title`"
author: "`r config_report$author`"
date: "`r config_report$date`"
output: html_document
css: custom.css
---

```{r setup, include=FALSE}
# Options
knitr::opts_chunk$set(echo = FALSE, fig.align = 'center',
	results = "asis", dpi = 150, warning = FALSE)
options(knitr.kable.NA = '')

# Packages to load
library(dplyr)
library(knitr)
library(kableExtra)
library(datascan)
library(purrr)

# Dataset and caracteristics
data <- if (!is.null(params$dataset)) {params$dataset} else {dplyr::starwars}
nr <- nrow(data)
nc <- ncol(data)
ncnum <- select_if(data, is.numeric) %>% ncol()
nccat <- select_if(data, ~is.factor(.x) | is.character(.x)) %>% ncol()

# Columns as responses ?
target <- params$target
target_cat <- select(data, !!!target) %>% 
  select_if(~is.factor(.x) | is.character(.x)) %>% 
  colnames()
ntarget_cat = length(target_cat)
target_num <- select(data, !!!target) %>% 
  select_if(is.numeric) %>% 
  colnames()
ntarget_num = length(target_num)

# Number of covariation plots
if (ntarget_cat != 0 & (nccat - ntarget_cat) != 0 ) {
  nplot_cc <- ntarget_cat*(nccat - ntarget_cat)
} else {
  nplot_cc <- choose(nccat, 2)
}
if (ntarget_num != 0 & (ncnum - ntarget_num) != 0 ) {
  nplot_nn <- ntarget_num*(ncnum - ntarget_num)
} else {
  nplot_nn <- choose(ncnum, 2)
}
if (ntarget_num != 0) {
  nplot_nc <- ntarget_num*nccat
} else {
  nplot_nc <- ncnum*nccat
}

# Regroup groups ?
regroup <- params$regroup
```

## Dataset

```{r general}
scd <- scan_data(data)
scc <- scan_columns(data)
```

### General status

```{r tab_scd}
scd %>% 
  kable(align = c("l", "r")) %>% 
  kable_styling(full_width = F, bootstrap_options = "condensed") %>% 
  add_indent(3:(nrow(scd) - 2)) %>%
  column_spec(1, bold = T)
```

### Columns status

```{r tab_scc}
scc %>% 
  select(-contains("p_")) %>% 
  mutate(
    Unique = .apply_colorbar(Unique, nr),
    NAs = .apply_colorbar(n_na, nr),
    Zeros = .apply_colorbar(n_0, nr),
    'Inf' = .apply_colorbar(n_Inf, nr)
  ) %>%
  select(-contains("n_")) %>%
  kable("html", escape = F, align = c("l", "l", rep("r",4))) %>% 
  kable_styling(full_width = F, bootstrap_options = "condensed") %>%
  column_spec(1, bold = T) %>% 
  column_spec(3:6, width = "70px")
```

## Variation

---
### Numerical columns
---

```{r ifnum}
if (ncnum > 0) {
  cat("### Numerical columns", fill = TRUE)
  cat("", fill = TRUE)
}
```

---
### Summary table
---

```{r ifnumtabletitle}
if (ncnum > 0) {
  cat("#### Summary table", fill = TRUE)
  cat("", fill = TRUE)
}
```


```{r ifnumtable}
if (ncnum > 0) {
  scan_numerics(data) %>%
  kable("html", escape = F, align = c("l", rep("r", 9)), digits = 2) %>% 
  kable_styling(full_width = F, bootstrap_options = "condensed")
}
```

---
#### Graphics
---

```{r ifnumplottitle}
if (ncnum > 0) {
  cat("#### Graphics", fill = TRUE)
  cat("", fill = TRUE)
}
```


```{r ifnumplot1, fig.width = 5, out.width = '50%', fig.asp = 0.8, fig.pos = 'center'}
if (ncnum == 1) {
  plotnum <- vis_numerics(data)
  walk(plotnum, plot)
}
```


<div class = "float_img">
```{r ifnumplot2+, fig.width = 5, out.width = '50%', fig.asp = 0.8}
if (ncnum > 1) {
  plotnum <- vis_numerics(data)
  walk(plotnum, plot)
}
```
</div>

---
### Categorical columns
---


```{r ifcatplottitle}
if (nccat > 0) {
  cat("### Categorical columns", fill = TRUE)
  cat("", fill = TRUE)
}
```



```{r ifcatplot1, fig.width = 5, out.width = '50%', fig.asp = 0.8, fig.pos = 'center'}
if (nccat == 1) {
  plotcat <- vis_groups(data)
  walk(plotcat, plot)
}
```



<div class = "float_img">
```{r ifcatplot2+, fig.width = 5, out.width = '50%', fig.asp = 0.8}
if (nccat > 1) {
  plotcat <- vis_groups(data)
  walk(plotcat, plot)
}
```
</div>

## Covariation

### Global covariations

---
#### Correlations
---

```{r corrtitle}
if (ncnum >= 2) {
  cat("#### Correlations", fill = TRUE)
  cat("", fill = TRUE)
}
```


```{r corr, out.width = '70%'}
if (ncnum >= 2) {
  vis_corr(data)
}
```

---
#### Bias corrected Cramer's V
---

```{r cramertitle}
if (nccat >= 2) {
  cat("#### Bias corrected Cramer's V", fill = TRUE)
  cat("", fill = TRUE)
}
```

```{r cramer, out.width = '70%'}
if (nccat >= 2) {
  vis_cramerv(data)
}
```

---
#### Linear R coefficient between numerical and categorical columns
---

```{r rlintitle}
if (nccat > 0 & ncnum > 0) {
  cat("#### Linear R coefficient between numerical and categorical columns", fill = TRUE)
  cat("", fill = TRUE)
}
```

```{r rlin, out.width = '70%'}
if (nccat > 0 & ncnum > 0) {
  vis_r(data)
}
```

### Specific covariations

---
#### Numerical ~ Numerical
---

```{r numnumtitle} 
if (nplot_nn > 0) {
  cat("#### Numerical ~ Numerical", fill = TRUE)
  cat("", fill = TRUE)
}
```


```{r numnum1, fig.width = 5, out.width = '50%', fig.asp = 0.8, fig.pos = 'center'} 
if (nplot_nn == 0) {
  plotnumnum <- vis_nncovar(data, !!!syms(target_num))
  walk(plotnumnum, plot)
}
```


<div class = "float_img">
```{r numnum2+, fig.width = 5, out.width = '50%', fig.asp = 0.8} 
if (nplot_nn > 1) {
  plotnumnum <- vis_nncovar(data, !!!syms(target_num))
  walk(plotnumnum, plot)
}
```
</div>

---
#### Numerical ~ Categorical
---

```{r numcattitle}
if (nplot_nc > 0) {
  cat("#### Numerical ~ Categorical", fill = TRUE)
  cat("", fill = TRUE)
}
```


```{r numcat1, fig.width = 5, out.width = '50%', fig.asp = 0.8, fig.pos = 'center'}
if (nplot_nc == 1) {
  plotnumcat <- vis_ngcovar(data,!!!syms(target_num), .regroup = regroup)
  walk(plotnumcat, plot)
}
```


<div class = "float_img">
```{r numcat2+, fig.width = 5, out.width = '50%', fig.asp = 0.8}
if (nplot_nc > 1) {
  plotnumcat <- vis_ngcovar(data,!!!syms(target_num), .regroup = regroup)
  walk(plotnumcat, plot)
}
```
</div>


---
#### Categorical ~ Categorical
---

```{r catcattitle}
if (nplot_cc > 0) {
  cat("#### Categorical ~ Categorical", fill = TRUE)
  cat("", fill = TRUE)
}
```


```{r catcat1, fig.width = 5, out.width = '50%', fig.asp = 0.8, fig.pos = 'center'}
if (nplot_cc == 1) {
  plotcatcat <- vis_ggcovar(data, !!!syms(target_cat), .regroup = regroup)
  walk(plotcatcat, plot)
}
```


<div class = "float_img">
```{r catcat2+, fig.width = 5, out.width = '50%', fig.asp = 0.8}
if (nplot_cc > 1) {
  plotcatcat <- vis_ggcovar(data, !!!syms(target_cat), .regroup = regroup)
  walk(plotcatcat, plot)
}
```
</div>

---
# Annexe
---

---
#```{r ifcattable}
# if (nccat > 0) {
#   cat("__Summary table__", fill = TRUE)
#   scan_groups(data) %>%
#     select(-p) %>%
#     mutate(
#       N = .apply_colorbar(n, nr)
#     )  %>%
#     select(-n) %>%
#     kable("html", escape = F, align = c("l", "l", rep("r", 2))) %>%
#     kable_styling(full_width = F, bootstrap_options = "condensed") %>%
#     column_spec(1, bold = T) %>% 
#     column_spec(3, width = "50px")
# }
#```
---


